// Database breakdown kanji per karakter — komponen, mnemonik, contoh kata
// Dipakai oleh nihongo_street_signs.html (harus di-host di folder yang sama)
const KANJI_DETAIL = {
"入": {c:[["入","piktograf pintu segitiga yang menyempit"]], mn:"Pintu segitiga yang menyempit ke dalam — orang melangkah MASUK lewat celah itu.", w:"入口", r:"いりぐち", wm:"Pintu masuk"},
"口": {c:[["口","piktograf mulut terbuka / kotak"]], mn:"Kotak sederhana ini gambar MULUT yang terbuka, bisa juga berarti 'lubang/ruang'.", w:"入口", r:"いりぐち", wm:"Pintu masuk"},
"出": {c:[["山","bentuk kaki melangkah"],["凵","lubang/wadah"]], mn:"Kaki melangkah KELUAR dari sebuah lubang/gua.", w:"出口", r:"でぐち", wm:"Pintu keluar"},
"非": {c:[["非","dua sayap burung yang membentang berlawanan arah"]], mn:"Dua sayap yang mengarah berlawanan — menggambarkan sesuatu yang BUKAN/bertentangan.", w:"非常口", r:"ひじょうぐち", wm:"Pintu darurat"},
"常": {c:[["尚","menghargai / di atas"],["巾","kain"]], mn:"KAIN (巾) yang selalu digantung tinggi dan dihargai (尚) — sesuatu yang tetap/BIASA ada.", w:"非常口", r:"ひじょうぐち", wm:"Pintu darurat"},
"営": {c:[["丷","dua api kecil"],["呂","susunan ruangan/markas"]], mn:"Dua api kecil menyala di sebuah markas (呂) — usaha yang terus dikelola.", w:"営業中", r:"えいぎょうちゅう", wm:"Sedang buka (toko)"},
"業": {c:[["業","piktograf alat/rangka kerja"]], mn:"Bentuknya seperti rangka alat kerja yang rumit — melambangkan USAHA/pekerjaan besar.", w:"営業中", r:"えいぎょうちゅう", wm:"Sedang buka (toko)"},
"中": {c:[["口","kotak/wilayah"],["丨","garis tegak menembus"]], mn:"Garis lurus menembus tepat di TENGAH kotak.", w:"営業中", r:"えいぎょうちゅう", wm:"Sedang buka (toko)"},
"準": {c:[["氵","air"],["隼","burung elang"]], mn:"Permukaan AIR yang rata dipakai sebagai patokan/STANDAR, setajam incaran elang (隼).", w:"準備中", r:"じゅんびちゅう", wm:"Sedang persiapan"},
"備": {c:[["人","orang"],["用+一","anak panah tersusun rapi"]], mn:"ORANG (人) menyiapkan anak panah tersusun rapi di kantongnya — LENGKAP siap dipakai.", w:"準備中", r:"じゅんびちゅう", wm:"Sedang persiapan"},
"定": {c:[["宀","atap"],["正","benar/lurus"]], mn:"Di bawah ATAP (宀), sesuatu yang sudah BENAR (正) posisinya — sudah ditetapkan.", w:"定休日", r:"ていきゅうび", wm:"Hari libur tetap"},
"休": {c:[["人","orang"],["木","pohon"]], mn:"ORANG bersandar di bawah POHON — sedang beristirahat.", w:"定休日", r:"ていきゅうび", wm:"Hari libur tetap"},
"日": {c:[["日","piktograf matahari bulat dengan garis tengah"]], mn:"Lingkaran dengan garis tengah — gambar MATAHARI, jadi juga berarti hari.", w:"定休日", r:"ていきゅうび", wm:"Hari libur tetap"},
"立": {c:[["立","piktograf orang berdiri tegak di atas tanah"]], mn:"Gambar orang BERDIRI tegak dengan kaki menapak di garis tanah.", w:"立入禁止", r:"たちいりきんし", wm:"Dilarang masuk"},
"禁": {c:[["林","dua pohon = hutan"],["示","altar/menunjukkan"]], mn:"Di tengah HUTAN (林) sakral ada ALTAR (示) — area yang dilarang untuk sembarang orang.", w:"立入禁止", r:"たちいりきんし", wm:"Dilarang masuk"},
"止": {c:[["止","piktograf jejak kaki yang berhenti melangkah"]], mn:"Gambar telapak kaki yang sedang BERHENTI, tidak melangkah lagi.", w:"立入禁止", r:"たちいりきんし", wm:"Dilarang masuk"},
"駐": {c:[["馬","kuda"],["主","tuan/pemilik"]], mn:"KUDA (馬) milik sang TUAN (主) diikat berhenti di satu titik — parkir.", w:"駐車禁止", r:"ちゅうしゃきんし", wm:"Dilarang parkir"},
"車": {c:[["車","piktograf roda kereta dilihat dari atas"]], mn:"Gambar RODA kereta/gerobak dilihat dari atas, dengan gandar di tengah.", w:"駐車禁止", r:"ちゅうしゃきんし", wm:"Dilarang parkir"},
"場": {c:[["土","tanah"],["昜","matahari terbit di atas altar"]], mn:"Sebidang TANAH terbuka yang tersinari matahari (昜) — sebuah TEMPAT.", w:"駐車場", r:"ちゅうしゃじょう", wm:"Tempat parkir"},
"一": {c:[["一","satu garis horizontal"]], mn:"Cuma satu garis lurus — angka SATU.", w:"一方通行", r:"いっぽうつうこう", wm:"Jalan satu arah"},
"方": {c:[["方","piktograf bajak/penanda arah"]], mn:"Bentuknya seperti tanda panah/bajak yang menunjukkan suatu ARAH.", w:"一方通行", r:"いっぽうつうこう", wm:"Jalan satu arah"},
"通": {c:[["辶","berjalan"],["甬","tabung/jalur"]], mn:"BERJALAN (辶) melewati sebuah jalur seperti tabung (甬) — melalui/lewat.", w:"一方通行", r:"いっぽうつうこう", wm:"Jalan satu arah"},
"行": {c:[["行","piktograf persimpangan jalan dari atas"]], mn:"Gambar sebuah PERSIMPANGAN jalan — tempat orang PERGI ke berbagai arah.", w:"一方通行", r:"いっぽうつうこう", wm:"Jalan satu arah"},
"徐": {c:[["彳","melangkah kecil"],["余","lebih/sisa"]], mn:"MELANGKAH (彳) dengan menyisakan (余) tenaga — berjalan PERLAHAN.", w:"徐行", r:"じょこう", wm:"Pelan-pelan"},
"横": {c:[["木","pohon/kayu"],["黄","kuning"]], mn:"Sebatang kayu (木) berwarna kuning (黄) diletakkan MELINTANG.", w:"横断歩道", r:"おうだんほどう", wm:"Zebra cross"},
"断": {c:[["米+ㄥ","benang yang terpotong"],["斤","kapak"]], mn:"KAPAK (斤) memotong putus seutas benang — MEMUTUS.", w:"横断歩道", r:"おうだんほどう", wm:"Zebra cross"},
"歩": {c:[["止","kaki/berhenti"],["少","bentuk kaki kedua"]], mn:"Dua bentuk kaki bergantian melangkah — MELANGKAH jalan kaki.", w:"横断歩道", r:"おうだんほどう", wm:"Zebra cross"},
"道": {c:[["辶","berjalan"],["首","kepala"]], mn:"KEPALA (首) memimpin langkah (辶) di sepanjang JALAN.", w:"横断歩道", r:"おうだんほどう", wm:"Zebra cross"},
"者": {c:[["耂","tua (dari 老)"],["日","bentuk mulut disederhanakan"]], mn:"Gambar ORANG tua yang duduk bercerita — pelaku suatu hal.", w:"歩行者専用", r:"ほこうしゃせんよう", wm:"Khusus pejalan kaki"},
"専": {c:[["甫","ladang/lapangan"],["寸","tangan/ukuran"]], mn:"TANGAN (寸) yang mengelola satu LADANG (甫) saja — fokus KHUSUS pada satu hal.", w:"歩行者専用", r:"ほこうしゃせんよう", wm:"Khusus pejalan kaki"},
"用": {c:[["用","piktograf wadah/ember"]], mn:"Gambar sebuah WADAH yang siap dipakai/DIGUNAKAN.", w:"歩行者専用", r:"ほこうしゃせんよう", wm:"Khusus pejalan kaki"},
"工": {c:[["工","piktograf alat tukang seperti penggaris siku"]], mn:"Bentuknya seperti alat tukang (penggaris siku) — dipakai untuk KONSTRUKSI.", w:"工事中", r:"こうじちゅう", wm:"Sedang ada konstruksi"},
"事": {c:[["⺕","tangan"],["亅+一","alat pencatat/bendera"]], mn:"TANGAN memegang alat pencatat — mengurus suatu URUSAN/hal.", w:"工事中", r:"こうじちゅう", wm:"Sedang ada konstruksi"},
"危": {c:[["勹","orang membungkuk di tebing"],["已","tubuh meringkuk"]], mn:"Orang membungkuk (勹) di tepi tebing curam — situasi BAHAYA.", w:"危険", r:"きけん", wm:"Bahaya"},
"険": {c:[["阝","bukit"],["僉","kumpul/banyak orang berdesakan"]], mn:"BUKIT (阝) yang curam, tempat banyak orang (僉) bisa terjatuh.", w:"危険", r:"きけん", wm:"Bahaya"},
"注": {c:[["氵","air"],["主","tuan/nyala lampu"]], mn:"Menuangkan AIR (氵) tepat ke satu titik seperti nyala lampu (主) — memusatkan perhatian.", w:"注意", r:"ちゅうい", wm:"Perhatian / hati-hati"},
"意": {c:[["音","suara"],["心","hati"]], mn:"SUARA (音) yang keluar dari HATI (心) — maksud/niat seseorang.", w:"注意", r:"ちゅうい", wm:"Perhatian / hati-hati"},
"火": {c:[["火","piktograf lidah api yang menyala"]], mn:"Gambar lidah API yang menyala ke atas.", w:"火気厳禁", r:"かきげんきん", wm:"Dilarang keras menyalakan api"},
"気": {c:[["气","uap yang mengepul"],["米","beras, kini disederhanakan"]], mn:"Uap (气) yang mengepul dari nasi (米) yang dimasak — UDARA/semangat.", w:"火気厳禁", r:"かきげんきん", wm:"Dilarang keras menyalakan api"},
"厳": {c:[["敢","berani bertindak"],["厂+山","tebing gunung bertumpuk"]], mn:"Berani (敢) menghadapi tebing gunung yang menjulang — sikap yang TEGAS/keras.", w:"火気厳禁", r:"かきげんきん", wm:"Dilarang keras menyalakan api"},
"喫": {c:[["口","mulut"],["契","kontrak/potong"]], mn:"MULUT (口) menghisap sesuatu seolah 'memotong' (契) asap masuk — merokok/minum.", w:"喫煙所", r:"きつえんじょ", wm:"Area merokok"},
"煙": {c:[["火","api"],["垔","menyumbat/berputar"]], mn:"API (火) yang menghasilkan kepulan yang menyumbat (垔) udara — ASAP.", w:"喫煙所", r:"きつえんじょ", wm:"Area merokok"},
"所": {c:[["戸","pintu rumah"],["斤","kapak"]], mn:"Di depan PINTU rumah (戸) tergantung sebuah kapak (斤) — menandai suatu TEMPAT.", w:"喫煙所", r:"きつえんじょ", wm:"Area merokok"},
"手": {c:[["手","piktograf jari-jari tangan terbuka"]], mn:"Gambar jari-jari TANGAN yang terbuka.", w:"お手洗い", r:"おてあらい", wm:"Kamar kecil (halus)"},
"洗": {c:[["氵","air"],["先","dulu/depan"]], mn:"Menyiramkan AIR (氵) lebih dulu (先) ke tangan — MENCUCI.", w:"お手洗い", r:"おてあらい", wm:"Kamar kecil (halus)"},
"案": {c:[["安","tenang, atap+wanita"],["木","kayu"]], mn:"Duduk TENANG (安) di meja KAYU (木) sambil menyusun rencana.", w:"案内所", r:"あんないじょ", wm:"Pusat informasi"},
"内": {c:[["冂","bingkai/pintu"],["入","masuk"]], mn:"Sesuatu yang MASUK (入) ke DALAM sebuah bingkai (冂).", w:"案内所", r:"あんないじょ", wm:"Pusat informasi"},
"両": {c:[["両","piktograf timbangan dua sisi seimbang"]], mn:"Gambar TIMBANGAN dengan dua sisi/pan yang sama — KEDUA-duanya.", w:"両替", r:"りょうがえ", wm:"Penukaran uang"},
"替": {c:[["夫夫","dua orang berdiri sejajar"],["日","matahari, dari 曰"]], mn:"Dua orang (夫夫) saling bertukar posisi di bawah matahari — MENGGANTI.", w:"両替", r:"りょうがえ", wm:"Penukaran uang"},
"割": {c:[["害","bahaya/rusak"],["刂","pisau"]], mn:"PISAU (刂) yang membuat sesuatu rusak (害) menjadi terpotong — MEMBAGI.", w:"割引", r:"わりびき", wm:"Diskon"},
"引": {c:[["弓","busur panah"],["|","tali yang ditarik lurus"]], mn:"Tali busur (弓) yang ditarik lurus (|) — MENARIK.", w:"割引", r:"わりびき", wm:"Diskon"},
"特": {c:[["牛","sapi"],["寺","kuil"]], mn:"SAPI (牛) kurban KHUSUS yang dipersembahkan di kuil (寺).", w:"特売", r:"とくばい", wm:"Obral / promo khusus"},
"売": {c:[["士","gentleman/atas"],["買 (disederhanakan)","barang dagangan"]], mn:"Seorang penjual (士) mengangkat barang dagangannya tinggi-tinggi — MENJUAL.", w:"特売", r:"とくばい", wm:"Obral / promo khusus"},
"新": {c:[["亲","kayu yang baru ditebang"],["斤","kapak"]], mn:"KAPAK (斤) menebang kayu — kayu yang BARU dipotong.", w:"新発売", r:"しんはつばい", wm:"Rilis baru"},
"発": {c:[["癶","dua kaki melangkah maju"],["弓+殳","busur dilepaskan"]], mn:"Dua kaki melangkah (癶) sambil melepaskan anak panah — BERANGKAT/menerbitkan.", w:"新発売", r:"しんはつばい", wm:"Rilis baru"},
"切": {c:[["七","bentuk sayatan"],["刀","pisau"]], mn:"PISAU (刀) menyayat (七) sesuatu jadi dua — MEMOTONG.", w:"売り切れ", r:"うりきれ", wm:"Habis terjual"},
"予": {c:[["予","piktograf alat tenun/pesawat kecil"]], mn:"Bentuknya seperti alat tenun yang disiapkan lebih dulu — SEBELUMNYA/rencana.", w:"予約席", r:"よやくせき", wm:"Kursi reservasi"},
"約": {c:[["糸","benang"],["勺","sendok kecil, ukuran"]], mn:"BENANG (糸) diikat dengan takaran (勺) yang pas — sebuah JANJI.", w:"予約席", r:"よやくせき", wm:"Kursi reservasi"},
"席": {c:[["广","atap/bangunan"],["巾","kain"]], mn:"Alas KAIN (巾) yang digelar di dalam sebuah bangunan (广) — TEMPAT DUDUK.", w:"予約席", r:"よやくせき", wm:"Kursi reservasi"},
"満": {c:[["氵","air"],["㒼","penuh sesak, simetris"]], mn:"AIR (氵) yang terisi sampai PENUH sesak ke tepi.", w:"満席", r:"まんせき", wm:"Penuh (kursi/tempat)"},
"空": {c:[["穴","lubang gua"],["工","alat tukang"]], mn:"Sebuah LUBANG gua (穴) yang digali dengan alat (工) — ruang KOSONG, seperti langit.", w:"空室", r:"くうしつ", wm:"Kamar kosong (hotel)"},
"室": {c:[["宀","atap"],["至","sampai/tiba"]], mn:"Tempat di bawah ATAP (宀) yang menjadi tujuan (至) — sebuah RUANGAN.", w:"空室", r:"くうしつ", wm:"Kamar kosong (hotel)"},
"貸": {c:[["代","mengganti/generasi"],["貝","uang kerang"]], mn:"UANG (貝) yang diganti (代) sementara ke orang lain — MEMINJAMKAN.", w:"貸切", r:"かしきり", wm:"Disewa penuh / private"},
"交": {c:[["交","piktograf kaki yang bersilangan"]], mn:"Gambar kaki yang BERSILANGAN/bertemu — bertukar atau bergaul.", w:"交番", r:"こうばん", wm:"Pos polisi"},
"番": {c:[["采","memilah dengan tangan"],["田","sawah"]], mn:"Memilah (采) petak-petak SAWAH (田) satu per satu sesuai NOMOR urut/giliran.", w:"交番", r:"こうばん", wm:"Pos polisi"},
"病": {c:[["疒","atap penyakit, orang berbaring"],["丙","urutan"]], mn:"Orang berbaring di atas dipan (疒) karena SAKIT.", w:"病院", r:"びょういん", wm:"Rumah sakit"},
"院": {c:[["阝","dinding tinggi"],["完","lengkap"]], mn:"Bangunan dengan DINDING (阝) tinggi yang lengkap (完) fasilitasnya — institusi besar.", w:"病院", r:"びょういん", wm:"Rumah sakit"},
"郵": {c:[["垂","menjuntai ke bawah"],["阝","kota/wilayah"]], mn:"Surat yang menjuntai (垂) dikirim antar KOTA (阝) — layanan POS.", w:"郵便局", r:"ゆうびんきょく", wm:"Kantor pos"},
"便": {c:[["人","orang"],["更","mengubah"]], mn:"ORANG (人) yang mengubah (更) sesuatu jadi lebih praktis — KENYAMANAN/pos.", w:"郵便局", r:"ゆうびんきょく", wm:"Kantor pos"},
"局": {c:[["尸","atap/tubuh"],["句","kalimat/kurva"]], mn:"Ruangan beratap (尸) tempat urusan tertulis (句) diproses — sebuah KANTOR.", w:"郵便局", r:"ゆうびんきょく", wm:"Kantor pos"},
"銀": {c:[["金","logam/emas"],["艮","keras kepala/berhenti"]], mn:"LOGAM (金) yang keras (艮) namun berkilau seperti perak.", w:"銀行", r:"ぎんこう", wm:"Bank"},
"薬": {c:[["艹","tumbuhan"],["楽","senang/musik"]], mn:"TUMBUHAN (艹) yang membuat orang jadi SENANG (楽) lagi karena sembuh — OBAT.", w:"薬局", r:"やっきょく", wm:"Apotek"},
"停": {c:[["人","orang"],["亭","paviliun/gazebo"]], mn:"ORANG (人) singgah BERHENTI sejenak di paviliun (亭) di pinggir jalan.", w:"停留所", r:"ていりゅうじょ", wm:"Halte bus"},
"留": {c:[["田","sawah"],["卯","dua sisi berlawanan"]], mn:"Sesuatu ditahan/ditanam di SAWAH (田) — TINGGAL di satu tempat.", w:"停留所", r:"ていりゅうじょ", wm:"Halte bus"},
"踏": {c:[["足","kaki"],["沓","tumpang tindih/berulang"]], mn:"KAKI (足) yang menapak berulang-ulang (沓) — MENGINJAK.", w:"踏切", r:"ふみきり", wm:"Perlintasan kereta"},
"落": {c:[["艹","tumbuhan/daun"],["洛","air sungai mengalir"]], mn:"Daun (艹) yang gugur mengikuti aliran air (洛) — JATUH.", w:"落石注意", r:"らくせきちゅうい", wm:"Awas batu jatuh"},
"石": {c:[["厂","tebing"],["口","bongkahan batu"]], mn:"Sebongkah BATU (口) di bawah tebing (厂).", w:"落石注意", r:"らくせきちゅうい", wm:"Awas batu jatuh"},
"迂": {c:[["辶","berjalan"],["于","melengkung"]], mn:"BERJALAN (辶) mengambil rute yang melengkung (于) — MEMUTAR.", w:"迂回", r:"うかい", wm:"Jalan memutar / alternatif"},
"回": {c:[["回","piktograf pusaran air dalam sebuah kotak"]], mn:"Gambar PUSARAN air yang berputar dalam kotak — PUTAR/kembali.", w:"迂回", r:"うかい", wm:"Jalan memutar / alternatif"},
"速": {c:[["辶","berjalan"],["束","ikatan kayu bakar"]], mn:"BERJALAN (辶) sambil membawa ikatan kayu (束) tanpa tercecer — CEPAT.", w:"速度制限", r:"そくどせいげん", wm:"Batas kecepatan"},
"度": {c:[["广","atap"],["廿+又","dua puluh + tangan mengukur"]], mn:"Di bawah ATAP (广), tangan mengukur (又) sesuatu berkali-kali — DERAJAT/kali.", w:"速度制限", r:"そくどせいげん", wm:"Batas kecepatan"},
"制": {c:[["未","belum/ranting"],["刂","pisau"]], mn:"PISAU (刂) memangkas ranting yang belum (未) rapi — mengontrol/membuat sistem.", w:"速度制限", r:"そくどせいげん", wm:"Batas kecepatan"},
"限": {c:[["阝","bukit"],["艮","berhenti/menoleh"]], mn:"BUKIT (阝) yang menjadi titik berhenti (艮) — sebuah BATAS.", w:"速度制限", r:"そくどせいげん", wm:"Batas kecepatan"},
"譲": {c:[["言","kata-kata"],["襄","melepaskan/membuka jalan"]], mn:"Dengan KATA-KATA (言) yang sopan, seseorang membuka jalan (襄) — MENGALAH.", w:"譲れ", r:"ゆずれ", wm:"Beri jalan (prioritas)"},
"私": {c:[["禾","padi"],["厶","milik pribadi"]], mn:"PADI (禾) hasil panen yang jadi milik PRIBADI (厶) — SAYA.", w:"私有地", r:"しゆうち", wm:"Tanah pribadi"},
"有": {c:[["月","daging/bulan"],["又","tangan"]], mn:"TANGAN (又) yang memegang sepotong daging (月) — MEMILIKI.", w:"私有地", r:"しゆうち", wm:"Tanah pribadi"},
"地": {c:[["土","tanah"],["也","partikel penegas"]], mn:"Permukaan TANAH (土) yang luas, seluas bumi (也).", w:"私有地", r:"しゆうち", wm:"Tanah pribadi"},
"監": {c:[["臣","mata besar/pejabat"],["皿","piring/wadah"]], mn:"MATA besar (臣) mengintip dari atas sebuah wadah (皿) — MENGAWASI.", w:"監視カメラ作動中", r:"かんしカメラさどうちゅう", wm:"CCTV sedang aktif"},
"視": {c:[["示","menunjukkan/altar"],["見","melihat"]], mn:"MELIHAT (見) dengan seksama untuk menunjukkan (示) sesuatu — MEMANDANG.", w:"監視カメラ作動中", r:"かんしカメラさどうちゅう", wm:"CCTV sedang aktif"},
"作": {c:[["人","orang"],["乍","tiba-tiba/memotong pola"]], mn:"ORANG (人) memotong pola (乍) untuk MEMBUAT sesuatu.", w:"監視カメラ作動中", r:"かんしカメラさどうちゅう", wm:"CCTV sedang aktif"},
"動": {c:[["重","berat"],["力","tenaga"]], mn:"Butuh TENAGA (力) besar untuk menggerakkan benda BERAT (重) — BERGERAK.", w:"監視カメラ作動中", r:"かんしカメラさどうちゅう", wm:"CCTV sedang aktif"},
"開": {c:[["門","pintu gerbang"],["廾","dua tangan mengangkat palang"]], mn:"Dua tangan mengangkat palang di PINTU GERBANG (門) — MEMBUKA.", w:"開店", r:"かいてん", wm:"Toko buka"},
"店": {c:[["广","atap/bangunan"],["占","menempati/meramal"]], mn:"Bangunan (广) yang ditempati (占) untuk berjualan — TOKO.", w:"開店", r:"かいてん", wm:"Toko buka"},
"閉": {c:[["門","pintu gerbang"],["才","palang kayu"]], mn:"Palang kayu (才) dipasang melintang di PINTU GERBANG (門) — MENUTUP.", w:"閉店", r:"へいてん", wm:"Toko tutup"},
"各": {c:[["夂","kaki melangkah turun"],["口","mulut/tempat"]], mn:"Setiap kaki (夂) melangkah menuju tempatnya (口) MASING-MASING.", w:"各種取扱", r:"かくしゅとりあつかい", wm:"Menjual / melayani berbagai jenis"},
"種": {c:[["禾","padi"],["重","berat/tumpukan"]], mn:"Tumpukan (重) biji PADI (禾) dari berbagai JENIS/benih.", w:"各種取扱", r:"かくしゅとりあつかい", wm:"Menjual / melayani berbagai jenis"},
"取": {c:[["耳","telinga"],["又","tangan"]], mn:"TANGAN (又) memegang TELINGA (耳) sebagai bukti tangkapan — MENGAMBIL.", w:"各種取扱", r:"かくしゅとりあつかい", wm:"Menjual / melayani berbagai jenis"},
"扱": {c:[["扌","tangan"],["及","mencapai/menyusul"]], mn:"TANGAN (扌) yang berusaha mencapai (及) dan mengurus sesuatu — MENANGANI.", w:"各種取扱", r:"かくしゅとりあつかい", wm:"Menjual / melayani berbagai jenis"},
"自": {c:[["自","piktograf hidung dari depan"]], mn:"Orang Jepang zaman dulu menunjuk HIDUNG saat bicara 'saya/DIRI SENDIRI'.", w:"自動販売機", r:"じどうはんばいき", wm:"Mesin penjual otomatis"},
"販": {c:[["貝","uang kerang"],["反","kebalikan/membalik"]], mn:"Membalikkan (反) barang menjadi UANG (貝) — BERDAGANG.", w:"自動販売機", r:"じどうはんばいき", wm:"Mesin penjual otomatis"},
"機": {c:[["木","kayu"],["幾","hampir/berapa"]], mn:"Rangka KAYU (木) dengan bagian rumit yang hampir (幾) tak terhitung — MESIN.", w:"自動販売機", r:"じどうはんばいき", wm:"Mesin penjual otomatis"},
"時": {c:[["日","matahari"],["寺","kuil, dulu 'mengukur'"]], mn:"Mengukur posisi MATAHARI (日) di kuil (寺) untuk tahu WAKTU.", w:"24時間営業", r:"にじゅうよじかんえいぎょう", wm:"Buka 24 jam"},
"間": {c:[["門","pintu gerbang"],["日","matahari"]], mn:"Sinar MATAHARI (日) yang menyusup lewat celah PINTU GERBANG (門) — jeda/ANTARA.", w:"24時間営業", r:"にじゅうよじかんえいぎょう", wm:"Buka 24 jam"},
"現": {c:[["王","raja/permata"],["見","melihat"]], mn:"MELIHAT (見) kilauan sebuah PERMATA (王) yang benar-benar NYATA.", w:"現金のみ", r:"げんきんのみ", wm:"Hanya tunai"},
"金": {c:[["金","piktograf bongkahan logam di dalam tanah"]], mn:"Gambar bongkahan LOGAM berharga yang terpendam di tanah — UANG.", w:"現金のみ", r:"げんきんのみ", wm:"Hanya tunai"},
"持": {c:[["扌","tangan"],["寺","kuil"]], mn:"TANGAN (扌) memegang erat sesuatu seperti menjaga KUIL (寺).", w:"お持ち帰り", r:"おもちかえり", wm:"Bawa pulang / take away"},
"帰": {c:[["巾","kain"],["帚","sapu"]], mn:"Membawa SAPU (帚) dan KAIN (巾) rumah tangga — kembali PULANG.", w:"お持ち帰り", r:"おもちかえり", wm:"Bawa pulang / take away"},
"料": {c:[["米","beras"],["斗","gayung/takaran"]], mn:"Mengukur BERAS (米) dengan gayung takaran (斗) — menghitung BIAYA/bahan.", w:"有料", r:"ゆうりょう", wm:"Berbayar"},
"無": {c:[["無","piktograf orang menari dengan kain terurai"]], mn:"Orang menari sampai kainnya lenyap terbang — jadi TIDAK ADA/kosong.", w:"無料", r:"むりょう", wm:"Gratis"},
"撮": {c:[["扌","tangan"],["最","paling/terbanyak"]], mn:"TANGAN (扌) menekan tombol mengambil momen yang PALING (最) tepat — MEMOTRET.", w:"撮影禁止", r:"さつえいきんし", wm:"Dilarang memotret"},
"影": {c:[["景","pemandangan"],["彡","garis cahaya/bulu"]], mn:"PEMANDANGAN (景) yang direkam lewat garis cahaya (彡) — BAYANGAN/foto.", w:"撮影禁止", r:"さつえいきんし", wm:"Dilarang memotret"},
"頭": {c:[["豆","kacang/wadah kecil"],["頁","kepala/halaman"]], mn:"Bentuk seperti wadah kecil (豆) di atas KEPALA (頁).", w:"頭上注意", r:"ずじょうちゅうい", wm:"Awas kepala terbentur"},
"上": {c:[["上","garis pendek di atas garis panjang"]], mn:"Garis pendek yang berada di ATAS garis dasar.", w:"頭上注意", r:"ずじょうちゅうい", wm:"Awas kepala terbentur"},
"段": {c:[["𠂉","tangga batu"],["殳","alat pemukul/tongkat"]], mn:"Anak tangga batu yang disusun bertingkat, dipahat dengan alat (殳) — TINGKAT.", w:"段差注意", r:"だんさちゅうい", wm:"Awas ada undakan"},
"差": {c:[["羊","domba, disederhanakan"],["工","alat ukur"]], mn:"Mengukur (alat 工) selisih antar dua DOMBA (羊) — PERBEDAAN.", w:"段差注意", r:"だんさちゅうい", wm:"Awas ada undakan"},
"濡": {c:[["氵","air"],["需","butuh, awan hujan"]], mn:"AIR hujan yang dibutuhkan (需) turun membuat semuanya BASAH.", w:"濡れています", r:"ぬれています", wm:"Lantai basah"},
"転": {c:[["車","kendaraan/roda"],["云","awan/berputar"]], mn:"RODA (車) yang berputar (云) — bergulir/berpindah.", w:"自転車専用", r:"じてんしゃせんよう", wm:"Khusus sepeda"},
"消": {c:[["氵","air"],["肖","kecil/menyusut"]], mn:"AIR (氵) yang membuat api menyusut kecil (肖) sampai padam — MEMADAMKAN.", w:"消火器", r:"しょうかき", wm:"Alat pemadam api"},
"器": {c:[["犬","anjing"],["口口口口","empat mulut/wadah"]], mn:"ANJING (犬) yang menjaga empat WADAH (口) berharga — ALAT.", w:"消火器", r:"しょうかき", wm:"Alat pemadam api"},
"避": {c:[["辶","berjalan"],["辟","menyingkir"]], mn:"BERJALAN (辶) menyingkir (辟) dari bahaya — MENGHINDAR.", w:"避難場所", r:"ひなんばしょ", wm:"Tempat evakuasi"},
"難": {c:[["隹","burung"],["堇","tanah liat/kesulitan"]], mn:"BURUNG (隹) yang sulit terbang dari tanah liat lengket (堇) — SULIT/bencana.", w:"避難場所", r:"ひなんばしょ", wm:"Tempat evakuasi"},
"給": {c:[["糸","benang"],["合","menggabungkan"]], mn:"Menggabungkan (合) BENANG (糸) menjadi satu pasokan yang cukup — MEMBERI.", w:"給油所", r:"きゅうゆじょ", wm:"SPBU"},
"油": {c:[["氵","air/cairan"],["由","dari/sebab"]], mn:"CAIRAN (氵) yang berasal dari (由) sumber tertentu — MINYAK.", w:"給油所", r:"きゅうゆじょ", wm:"SPBU"},
"温": {c:[["氵","air"],["昷","matahari di atas piring"]], mn:"AIR (氵) yang dihangatkan seperti sup di atas piring (昷) — HANGAT.", w:"温泉", r:"おんせん", wm:"Pemandian air panas"},
"泉": {c:[["白","putih/bersih"],["水","air"]], mn:"AIR (水) yang jernih dan PUTIH (白) mengalir dari sumbernya — MATA AIR.", w:"温泉", r:"おんせん", wm:"Pemandian air panas"},
"神": {c:[["示","altar"],["申","petir/memperluas"]], mn:"PETIR (申) yang menyambar dari langit dianggap tanda ALTAR (示) para DEWA.", w:"神社", r:"じんじゃ", wm:"Kuil Shinto"},
"社": {c:[["示","altar"],["土","tanah"]], mn:"ALTAR (示) yang dibangun di atas sebidang TANAH (土) — KUIL/organisasi.", w:"神社", r:"じんじゃ", wm:"Kuil Shinto"},
"寺": {c:[["土","tanah, dulu tangan"],["寸","tangan/ukuran"]], mn:"TANGAN (寸) yang mengurus tanah suci sebuah lembaga — KUIL.", w:"お寺", r:"おてら", wm:"Kuil Buddha"},
"展": {c:[["尸","tubuh/atap"],["𧘇","kain terbentang"]], mn:"TUBUH (尸) merentangkan sesuatu lebar-lebar untuk dipamerkan.", w:"展望台", r:"てんぼうだい", wm:"Dek pemandangan"},
"望": {c:[["亡","hilang dari pandangan"],["月","bulan"],["王","berdiri tegak"]], mn:"Berdiri tegak (王) memandang BULAN (月) yang nyaris hilang (亡) di kejauhan — HARAPAN.", w:"展望台", r:"てんぼうだい", wm:"Dek pemandangan"},
"台": {c:[["厶","pribadi"],["口","mulut/dasar"]], mn:"Sebuah dasar (口) pribadi (厶) tempat berdiri — PLATFORM/dudukan.", w:"展望台", r:"てんぼうだい", wm:"Dek pemandangan"},
"進": {c:[["辶","berjalan"],["隹","burung"]], mn:"BURUNG (隹) yang hanya bisa terbang MAJU (辶), tidak mundur.", w:"車両進入禁止", r:"しゃりょうしんにゅうきんし", wm:"Kendaraan dilarang masuk"},
"物": {c:[["牛","sapi"],["勿","jangan/beragam warna"]], mn:"SAPI (牛) dengan beragam warna (勿) — mewakili segala jenis BENDA/makhluk.", w:"動物注意", r:"どうぶつちゅうい", wm:"Awas hewan menyeberang"},
"使": {c:[["人","orang"],["吏","pejabat"]], mn:"ORANG (人) diperintah seperti PEJABAT (吏) yang menjalankan tugas — MENGGUNAKAN/menyuruh.", w:"使用中", r:"しようちゅう", wm:"Sedang digunakan"},
"故": {c:[["古","lama/kuno"],["攵","tindakan ringan"]], mn:"Kejadian LAMA (古) yang memicu suatu tindakan (攵) — SEBAB.", w:"故障中", r:"こしょうちゅう", wm:"Sedang rusak"},
"障": {c:[["阝","bukit/dinding"],["章","bab/lencana"]], mn:"DINDING (阝) tinggi seperti penanda bab (章) yang menghalangi jalan — HALANGAN.", w:"故障中", r:"こしょうちゅう", wm:"Sedang rusak"},
"会": {c:[["人","orang, bentuk tutup"],["云","awan/berkumpul"]], mn:"Orang-orang (人) berkumpul seperti awan (云) menyatu — BERTEMU.", w:"お会計はこちら", r:"おかいけいはこちら", wm:"Kasir di sini"},
"計": {c:[["言","kata-kata"],["十","sepuluh"]], mn:"Mengucapkan (言) angka sampai SEPULUH (十) — MENGHITUNG.", w:"お会計はこちら", r:"おかいけいはこちら", wm:"Kasir di sini"},
"同": {c:[["冂","bingkai"],["一+口","garis dan mulut sejajar"]], mn:"Semua berada dalam satu BINGKAI (冂) yang SAMA.", w:"ペット同伴可", r:"ペットどうはんか", wm:"Boleh bawa hewan peliharaan"},
"伴": {c:[["人","orang"],["半","setengah"]], mn:"ORANG (人) yang berbagi SETENGAH (半) perjalanan — MENEMANI.", w:"ペット同伴可", r:"ペットどうはんか", wm:"Boleh bawa hewan peliharaan"},
"可": {c:[["口","mulut"],["丂","suara tertahan/menyetujui"]], mn:"MULUT (口) yang mengucapkan persetujuan — BOLEH.", w:"ペット同伴可", r:"ペットどうはんか", wm:"Boleh bawa hewan peliharaan"},
};
