(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=$('#app'), questions=window.N3_QUESTIONS, terms=window.N3_TERMS;
const SECTIONS={vocab:'Kosakata',grammar:'Tata bahasa',reading:'Membaca',listening:'Mendengar'};
const DEFAULT={version:1,createdAt:Date.now(),lastStudy:null,streak:0,days:[],cards:{},sessions:[],active:null,settings:{dailyGoal:15}};
let state=DEFAULT, view='home', session=null, installPrompt=null, saveTimer=null, timerRun=0;

const Store={
  db:null,
  async open(){return new Promise((resolve,reject)=>{const req=indexedDB.open('renshuu-n3',1);req.onupgradeneeded=()=>req.result.createObjectStore('state');req.onsuccess=()=>{this.db=req.result;resolve()};req.onerror=()=>reject(req.error)})},
  async get(){return new Promise(resolve=>{const req=this.db.transaction('state').objectStore('state').get('main');req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null)})},
  async set(value){return new Promise((resolve,reject)=>{const tx=this.db.transaction('state','readwrite');tx.objectStore('state').put(value,'main');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
function touchDay(){const d=today();if(!state.days.includes(d))state.days.push(d);const sorted=[...state.days].sort();let streak=0,cur=new Date();for(let i=sorted.length-1;i>=0;i--){const x=cur.toISOString().slice(0,10);if(sorted.includes(x)){streak++;cur.setDate(cur.getDate()-1)}else if(i===sorted.length-1){cur.setDate(cur.getDate()-1);i++}else break}state.streak=streak;state.lastStudy=Date.now()}
function scheduleSave(){clearTimeout(saveTimer);$('#saveState').textContent='● menyimpan…';saveTimer=setTimeout(async()=>{await Store.set(state);$('#saveState').textContent='● tersimpan'},180)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function progressOf(id){return state.cards[id]||{seen:0,correct:0,streak:0,ease:2.3,interval:0,due:0,lastAnswer:null}}
function dueQuestions(section){return questions.filter(q=>(!section||q.section===section)&&progressOf(q.id).due<=Date.now())}
function mastery(section){const arr=questions.filter(q=>!section||q.section===section);return Math.round(arr.reduce((n,q)=>{const p=progressOf(q.id);return n+Math.min(1,(p.correct||0)/3)},0)/arr.length*100)||0}
function mark(q,correct,choice){const p=progressOf(q.id);p.seen++;p.lastAnswer=choice;p.lastAt=Date.now();if(correct){p.correct++;p.streak++;p.interval=p.streak===1?1:p.streak===2?3:Math.max(5,Math.round((p.interval||3)*p.ease));p.ease=Math.min(2.8,p.ease+.05)}else{p.streak=0;p.interval=0;p.ease=Math.max(1.6,p.ease-.18)}p.due=Date.now()+p.interval*86400000;state.cards[q.id]=p;touchDay();scheduleSave()}
function linkTerms(text,list=[]){let html=esc(text);[...new Set(list)].sort((a,b)=>b.length-a.length).forEach(term=>{html=html.replaceAll(esc(term),`<button class="term" data-term="${esc(term)}">${esc(term)}</button>`)});return html}
function setView(name){view=name;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo(0,0);render()}
function sectionCards(){return Object.entries(SECTIONS).map(([key,label],i)=>`<article class="card route-card"><span class="num">${i+1}</span><h3>${label}</h3><p>${dueQuestions(key).length} soal jatuh tempo · penguasaan ${mastery(key)}%</p><footer><div class="progress" style="width:56%"><span style="width:${mastery(key)}%"></span></div><button class="button small ghost" data-start="practice" data-section="${key}">Mulai</button></footer></article>`).join('')}
function home(){const seen=Object.values(state.cards).filter(x=>x.seen).length,errors=Object.values(state.cards).reduce((n,x)=>n+Math.max(0,x.seen-x.correct),0);return `
  ${state.active?`<div class="card resume"><div><b>Ada sesi belum selesai</b><br><small>${state.active.mode==='mock'?'Simulasi ujian':'Latihan'} · nomor ${(state.active.index||0)+1} dari ${state.active.ids.length}</small></div><button class="button small" id="resumeBtn">Lanjutkan</button></div>`:''}
  <section class="hero"><article class="card"><p class="eyebrow">今日の一歩 · langkah hari ini</p><h1>15 menit lebih dekat ke <span style="color:var(--red)">N3</span>.</h1><p>Kerjakan soal yang hampir terlupa dulu. Sistem akan mengulang kesalahan pada waktu yang tepat dan mencampur kosakata, tata bahasa, membaca, serta mendengar.</p><div class="actions"><button class="button" data-start="daily">Mulai sesi 15 menit</button><button class="button secondary" data-start="diagnostic">Tes diagnostik</button></div></article><article class="card streak"><small>STREAK BELAJAR</small><strong>${state.streak}</strong><span>hari</span></article></section>
  <section class="grid"><article class="card metric"><strong>${dueQuestions().length}</strong><span>perlu diulang hari ini</span></article><article class="card metric"><strong>${seen}/${questions.length}</strong><span>soal pernah dikerjakan</span></article><article class="card metric"><strong>${errors}</strong><span>jawaban salah tercatat</span></article></section>
  <div class="section-head"><div><p class="eyebrow">PETA KEMAMPUAN</p><h2>Empat bidang N3</h2></div><p>Klik bidang untuk latihan terarah</p></div><section class="grid">${sectionCards()}</section>
  <div class="section-head"><div><p class="eyebrow">METODE</p><h2>Kenapa urutannya begini?</h2></div></div><section class="mode-grid"><article class="card"><b>1 · Coba ingat dulu</b><p>Menjawab sebelum melihat penjelasan melatih retrieval, kemampuan yang benar-benar dibutuhkan saat ujian.</p></article><article class="card"><b>2 · Koreksi segera</b><p>Mode latihan langsung menjelaskan kesalahan agar jawaban keliru tidak menetap.</p></article><article class="card"><b>3 · Ulang setelah jeda</b><p>Soal yang salah kembali lebih cepat; soal yang dikuasai diberi jarak lebih panjang.</p></article><article class="card"><b>4 · Uji tanpa bantuan</b><p>Simulasi menyembunyikan hasil sampai akhir, memakai batas waktu dan evaluasi per bidang.</p></article></section>`}
function learn(){return `<div class="section-head"><div><p class="eyebrow">BELAJAR TERARAH</p><h2>Pilih jalur yang ringan untuk mulai</h2></div></div><section class="mode-grid">
  <article class="card mode-card" data-start="due"><span class="mode-icon">↻</span><h3>Ulang yang hampir lupa</h3><p>${dueQuestions().length} soal sudah jatuh tempo. Prioritas terbaik hari ini.</p></article>
  <article class="card mode-card" data-start="mistakes"><span class="mode-icon">△</span><h3>Perbaiki kesalahan</h3><p>Latih kembali soal yang pernah salah dengan penjelasan langsung.</p></article>
  <article class="card mode-card" data-start="vocab"><span class="mode-icon">字</span><h3>Kanji & kosakata</h3><p>Klik kata bergaris bawah kapan saja untuk melihat cara baca, arti, dan contoh.</p></article>
  <article class="card mode-card" data-start="grammar"><span class="mode-icon">文</span><h3>Pola kalimat</h3><p>Latihan bentuk, susunan kalimat, dan tata bahasa dalam teks.</p></article>
  <article class="card mode-card" data-start="reading"><span class="mode-icon">読</span><h3>Reading bertempo</h3><p>Teks pendek, menengah, panjang, dan pencarian informasi.</p></article>
  <article class="card mode-card" data-start="listening"><span class="mode-icon">聴</span><h3>Listening aktif</h3><p>Dengarkan TTS Jepang tanpa melihat transkrip, lalu pilih maksudnya.</p></article></section>`}
function practice(){return `<div class="section-head"><div><p class="eyebrow">LATIHAN SOAL</p><h2>Format yang diuji di N3</h2></div><p>Umpan balik langsung aktif</p></div><section class="grid">${sectionCards()}</section><article class="card" style="margin-top:18px"><h3>Catatan keaslian</h3><p>Semua soal di aplikasi ini ditulis orisinal dengan tipe tugas resmi N3: bacaan kanji, ortografi, ekspresi kontekstual, parafrasa, penggunaan, bentuk tata bahasa, susunan kalimat, tata bahasa teks, reading, dan lima tipe listening. Ini bukan bocoran maupun salinan ujian resmi.</p></article>`}
function mock(){return `<section class="hero"><article class="card"><p class="eyebrow">本番モード · mode ujian</p><h1>Simulasi N3</h1><p>Tidak ada jawaban benar, kamus klik, atau penjelasan selama ujian. Nilai dan evaluasi baru muncul setelah seluruh simulasi dikumpulkan.</p><div class="mock-warning"><b>Format resmi:</b> kosakata 30 menit · tata bahasa & membaca 70 menit · mendengar 40 menit.</div><div class="actions"><button class="button" data-start="mock">Ringkas · 30 soal / 45 menit</button><button class="button ghost" data-start="mock-full">Penuh · 50 soal / 140 menit</button></div></article><article class="card"><h3>Standar lulus resmi</h3><p><b>95 / 180</b> total, sekaligus minimal <b>19 / 60</b> pada Bahasa, Membaca, dan Mendengar.</p><p class="pill">Nilai aplikasi = estimasi latihan</p><p style="font-size:12px;color:var(--muted)">JLPT memakai scaled score, sehingga persentase benar di sini tidak sama persis dengan nilai resmi.</p></article></section>`}
function review(){const latest=state.sessions[0];const wrong=questions.filter(q=>{const p=progressOf(q.id);return p.seen>p.correct});return `<div class="section-head"><div><p class="eyebrow">EVALUASI</p><h2>Peta kelemahanmu</h2></div><button id="backupBtn" class="button small ghost">Unduh backup progres</button></div>
  <section class="grid">${Object.entries(SECTIONS).map(([k,v])=>`<article class="card metric"><strong>${mastery(k)}%</strong><span>${v}</span><div class="progress" style="margin-top:12px"><span style="width:${mastery(k)}%"></span></div></article>`).join('')}</section>
  ${latest?`<article class="card" style="margin-top:18px"><h3>Simulasi terakhir · ${new Date(latest.at).toLocaleDateString('id-ID')}</h3><div class="breakdown">${Object.entries(latest.scores).map(([k,v])=>`<div class="card"><strong>${v}/60</strong><span>${SECTIONS[k]||k}</span></div>`).join('')}</div><p><b>${latest.pass?'LULUS latihan':'BELUM lulus'}</b> · total ${latest.total}/180</p></article>`:''}
  <article class="card" style="margin-top:18px"><h3>Log kesalahan (${wrong.length})</h3>${wrong.length?wrong.slice(0,20).map(q=>`<div class="error-item"><h4>${linkTerms(q.prompt,q.terms)}</h4><p>${SECTIONS[q.section]} · ${q.type}</p><p>${esc(q.explanation)}</p><button class="button small ghost" data-single="${q.id}">Latih lagi</button></div>`).join(''):'<div class="empty">Belum ada kesalahan tercatat. Coba tes diagnostik dulu.</div>'}</article>
  <article class="card" style="margin-top:18px"><h3>Sumber & dasar desain</h3><ul class="source-list"><li><a href="https://www.jlpt.jp/e/guideline/testsections.html" target="_blank" rel="noreferrer">JLPT — komposisi dan waktu tes resmi</a></li><li><a href="https://www.jlpt.jp/e/guideline/results.html" target="_blank" rel="noreferrer">JLPT — skor dan standar kelulusan</a></li><li><a href="https://www.jlpt.jp/e/samples/sampleindex.html" target="_blank" rel="noreferrer">JLPT — Official Practice Workbook</a></li><li><a href="https://www.nature.com/articles/s44159-022-00089-1" target="_blank" rel="noreferrer">Carpenter, Pan & Butler (2022) — spacing dan retrieval practice</a></li></ul></article>`}

function start(kind,section){let pool=[...questions],limit=12,mode='practice',minutes=null,keepOrder=false;if(kind==='daily'){pool=[...dueQuestions()];if(pool.length<15)pool.push(...questions.filter(q=>!pool.includes(q)));limit=15}else if(kind==='diagnostic'){limit=16;pool=interleave(questions)}else if(kind==='due')pool=dueQuestions();else if(kind==='mistakes')pool=questions.filter(q=>{const p=progressOf(q.id);return p.seen>p.correct});else if(['vocab','grammar','reading','listening'].includes(kind)){section=kind;pool=questions.filter(q=>q.section===section)}else if(kind==='practice')pool=questions.filter(q=>q.section===section);else if(kind==='mock'){mode='mock';minutes=45;limit=30;keepOrder=true;pool=examOrder(questions).filter((q,i)=>i%2===0).slice(0,30)}else if(kind==='mock-full'){mode='mock';minutes=140;limit=questions.length;keepOrder=true;pool=examOrder(questions)}else if(kind.startsWith('single:')){pool=questions.filter(q=>q.id===kind.slice(7));limit=1}if(!pool.length){toast('Belum ada soal di antrean ini');return}pool=(keepOrder?pool:interleave(pool)).slice(0,limit);session={mode,ids:pool.map(q=>q.id),index:0,answers:{},checked:{},startedAt:Date.now(),endAt:minutes?Date.now()+minutes*60000:null};state.active=session;scheduleSave();renderQuiz()}
function examOrder(arr){return [...arr].sort((a,b)=>({vocab:0,grammar:1,reading:2,listening:3}[a.section]-({vocab:0,grammar:1,reading:2,listening:3}[b.section])))}
function interleave(arr){const groups={};arr.forEach(q=>(groups[q.section]??=[]).push(q));Object.values(groups).forEach(a=>a.sort(()=>Math.random()-.5));const out=[];while(Object.values(groups).some(a=>a.length))Object.values(groups).forEach(a=>a.length&&out.push(a.shift()));return out}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.88;speechSynthesis.speak(u)}
function renderQuiz(){const q=questions.find(x=>x.id===session.ids[session.index]),chosen=session.answers[q.id],checked=session.checked[q.id],mock=session.mode==='mock';const remain=session.endAt?Math.max(0,session.endAt-Date.now()):0;app.innerHTML=`<section class="quiz-shell"><div class="quiz-top"><span>${SECTIONS[q.section]} · ${q.type}</span><span>${session.index+1} / ${session.ids.length}${mock?` · <b class="timer" data-end="${session.endAt}">${timeText(remain)}</b>`:''}</span></div><div class="progress"><span style="width:${(session.index+1)/session.ids.length*100}%"></span></div><article class="card" style="margin-top:14px">${q.audio?`<button class="button secondary" id="audioBtn">▶ Putar audio Jepang</button><p style="font-size:12px;color:var(--muted)">${mock?'Transkrip disembunyikan selama simulasi.':'Dengarkan tanpa melihat transkrip terlebih dahulu.'}</p>`:''}${q.passage?`<div class="passage">${mock?esc(q.passage):linkTerms(q.passage,q.terms)}</div>`:''}<div class="question">${mock?esc(q.prompt):linkTerms(q.prompt,q.terms)}</div><div class="options">${q.options.map((o,i)=>`<button class="option ${chosen===i?'selected':''} ${checked&&i===q.answer?'correct':''} ${checked&&chosen===i&&i!==q.answer?'wrong':''}" data-choice="${i}" ${checked?'disabled':''}><span class="option-key">${i+1}</span><span>${esc(o)}</span></button>`).join('')}</div>${checked?`<div class="explanation"><b>${chosen===q.answer?'Benar':'Belum tepat'}.</b> ${esc(q.explanation)}${q.audio?`<details><summary>Lihat transkrip</summary><p>${esc(q.audio)}</p></details>`:''}</div>`:''}<footer class="quiz-footer"><button class="button ghost" id="quitBtn">Simpan & keluar</button>${mock?`<button class="button" id="nextBtn" ${chosen==null?'disabled':''}>${session.index===session.ids.length-1?'Kumpulkan':'Berikutnya'}</button>`:checked?`<button class="button" id="nextBtn">${session.index===session.ids.length-1?'Selesai':'Berikutnya'}</button>`:`<button class="button" id="checkBtn" ${chosen==null?'disabled':''}>Periksa</button>`}</footer></article></section>`;bindQuiz(q);if(mock)startTimer()}
function bindQuiz(q){$$('[data-choice]').forEach(b=>b.onclick=()=>{session.answers[q.id]=+b.dataset.choice;state.active=session;scheduleSave();renderQuiz()});$('#audioBtn')?.addEventListener('click',()=>speak(q.audio));$('#quitBtn').onclick=()=>{state.active=session;scheduleSave();setView('home')};$('#checkBtn')?.addEventListener('click',()=>{session.checked[q.id]=true;mark(q,session.answers[q.id]===q.answer,session.answers[q.id]);state.active=session;renderQuiz()});$('#nextBtn')?.addEventListener('click',()=>{if(session.index===session.ids.length-1)finishSession();else{session.index++;state.active=session;scheduleSave();renderQuiz()}});bindTerms()}
function finishSession(){if(session.mode==='mock'){const result=scoreMock();state.sessions.unshift(result);state.sessions=state.sessions.slice(0,20);session.ids.forEach(id=>{const q=questions.find(x=>x.id===id);mark(q,session.answers[id]===q.answer,session.answers[id])});state.active=null;session=null;scheduleSave();renderResult(result)}else{state.active=null;session=null;scheduleSave();toast('Sesi selesai — progres tersimpan');setView('review')}}
function scoreMock(){const groups={vocab:[],grammar:[],reading:[],listening:[]};session.ids.forEach(id=>{const q=questions.find(x=>x.id===id);groups[q.section].push(session.answers[id]===q.answer)});const lang=[...groups.vocab,...groups.grammar];const calc=a=>a.length?Math.round(a.filter(Boolean).length/a.length*60):0;const scores={language:calc(lang),reading:calc(groups.reading),listening:calc(groups.listening)},total=Object.values(scores).reduce((a,b)=>a+b,0);return{at:Date.now(),scores,total,pass:total>=95&&Object.values(scores).every(x=>x>=19),answers:{...session.answers},ids:[...session.ids]}}
function renderResult(r){app.innerHTML=`<section class="quiz-shell"><article class="card" style="text-align:center"><p class="eyebrow">HASIL SIMULASI</p><div class="score-ring" style="--score:${Math.round(r.total/180*100)}%"><strong>${r.total}</strong></div><h1>${r.pass?'合格 · Lulus latihan':'あと少し · Belum lulus'}</h1><p>Estimasi ${r.total}/180. Ini skor latihan berbasis persentase benar, bukan scaled score resmi JLPT.</p><div class="breakdown">${Object.entries(r.scores).map(([k,v])=>`<div class="card"><strong>${v}/60</strong><span>${SECTIONS[k]||({language:'Bahasa'}[k])}</span><small>${v>=19?'batas bagian aman':'di bawah 19'}</small></div>`).join('')}</div><div class="actions" style="justify-content:center"><button class="button" id="evalBtn">Lihat evaluasi lengkap</button><button class="button ghost" id="homeBtn">Kembali</button></div></article></section>`;$('#evalBtn').onclick=()=>setView('review');$('#homeBtn').onclick=()=>setView('home')}
function timeText(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60);return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function startTimer(){const el=$('.timer');if(!el)return;const run=++timerRun;const tick=()=>{if(run!==timerRun||!session||session.mode!=='mock')return;const left=session.endAt-Date.now();el.textContent=timeText(Math.max(0,left));if(left<=0){finishSession();return}setTimeout(tick,1000)};tick()}
function bindTerms(){$$('[data-term]').forEach(b=>b.onclick=e=>{e.stopPropagation();openTerm(b.dataset.term)})}
function openTerm(key){const t=terms[key];if(!t)return;$('#termContent').innerHTML=`<p class="eyebrow">KARTU KATA</p><div class="term-big">${esc(key)}</div><div class="reading">${esc(t.reading)}</div><h3>${esc(t.meaning)}</h3><div class="example"><b>${esc(t.example)}</b><br><span>${esc(t.translation)}</span></div><div class="actions"><button class="button secondary" id="speakTerm">▶ Dengarkan</button><button class="button" id="addReview">＋ Ulang nanti</button></div>`;$('#termSheet').classList.add('open');$('#termSheet').setAttribute('aria-hidden','false');$('#speakTerm').onclick=()=>speak(key+'。'+t.example);$('#addReview').onclick=()=>{questions.filter(q=>q.terms?.includes(key)).forEach(q=>{const p=progressOf(q.id);p.due=0;state.cards[q.id]=p});scheduleSave();toast('Ditambahkan ke antrean ulang')}}
function closeTerm(){$('#termSheet').classList.remove('open');$('#termSheet').setAttribute('aria-hidden','true')}
function backup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`renshuu-n3-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function bind(){$$('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start,b.dataset.section));$$('[data-single]').forEach(b=>b.onclick=()=>start('single:'+b.dataset.single));$('#resumeBtn')?.addEventListener('click',()=>{session=state.active;renderQuiz()});$('#backupBtn')?.addEventListener('click',backup);bindTerms()}
function render(){app.innerHTML=({home,learn,practice,mock,review}[view])();bind()}
$$('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('.sheet-close').onclick=closeTerm;$('.sheet-backdrop').onclick=closeTerm;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTerm()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
(async()=>{try{await Store.open();state={...DEFAULT,...(await Store.get()||{})};if(state.active){session=state.active}render()}catch(e){console.error(e);app.innerHTML='<div class="card">Penyimpanan browser tidak tersedia. Buka lewat server lokal atau HTTPS.</div>'}})();
})();
