/* Soal orisinal bergaya JLPT N3. Bukan soal bocoran atau salinan ujian resmi. */
window.N3_TERMS={
  "締切":{reading:"しめきり",meaning:"batas waktu",example:"レポートの締切は金曜日です。",translation:"Batas waktu laporan adalah hari Jumat."},
  "延期":{reading:"えんき",meaning:"penundaan",example:"雨で試合が延期になりました。",translation:"Pertandingan ditunda karena hujan."},
  "到着":{reading:"とうちゃく",meaning:"tiba / kedatangan",example:"電車は九時に到着します。",translation:"Kereta tiba pukul sembilan."},
  "確認":{reading:"かくにん",meaning:"konfirmasi / memastikan",example:"時間をもう一度確認してください。",translation:"Tolong pastikan waktunya sekali lagi."},
  "準備":{reading:"じゅんび",meaning:"persiapan",example:"旅行の準備はできましたか。",translation:"Apakah persiapan perjalanannya sudah selesai?"},
  "断る":{reading:"ことわる",meaning:"menolak",example:"忙しかったので、誘いを断りました。",translation:"Karena sibuk, saya menolak ajakannya."},
  "間に合う":{reading:"まにあう",meaning:"tepat waktu / keburu",example:"走れば電車に間に合います。",translation:"Kalau berlari, kita akan keburu kereta."},
  "効果":{reading:"こうか",meaning:"efek / khasiat",example:"この薬は効果があります。",translation:"Obat ini berkhasiat."},
  "増加":{reading:"ぞうか",meaning:"peningkatan",example:"外国人観光客が増加しています。",translation:"Wisatawan asing sedang meningkat."},
  "減少":{reading:"げんしょう",meaning:"penurunan",example:"人口が減少しています。",translation:"Populasi sedang menurun."},
  "環境":{reading:"かんきょう",meaning:"lingkungan",example:"環境を守るためにごみを減らします。",translation:"Kami mengurangi sampah untuk menjaga lingkungan."},
  "経験":{reading:"けいけん",meaning:"pengalaman",example:"日本で働いた経験があります。",translation:"Saya punya pengalaman bekerja di Jepang."},
  "応募":{reading:"おうぼ",meaning:"melamar / mendaftar",example:"アルバイトに応募しました。",translation:"Saya melamar kerja paruh waktu."},
  "提出":{reading:"ていしゅつ",meaning:"menyerahkan",example:"書類を明日までに提出してください。",translation:"Tolong serahkan dokumen paling lambat besok."},
  "変更":{reading:"へんこう",meaning:"perubahan",example:"予定が変更になりました。",translation:"Jadwalnya berubah."},
  "利用":{reading:"りよう",meaning:"penggunaan / memakai",example:"図書館をよく利用します。",translation:"Saya sering menggunakan perpustakaan."},
  "故障":{reading:"こしょう",meaning:"kerusakan mesin",example:"エレベーターが故障しています。",translation:"Lif sedang rusak."},
  "混雑":{reading:"こんざつ",meaning:"keramaian / padat",example:"駅は朝とても混雑します。",translation:"Stasiun sangat padat pada pagi hari."},
  "念のため":{reading:"ねんのため",meaning:"untuk berjaga-jaga",example:"念のため傘を持っていきます。",translation:"Untuk berjaga-jaga saya membawa payung."},
  "せっかく":{reading:"せっかく",meaning:"mumpung / sudah susah payah",example:"せっかく来たので、ゆっくり見ましょう。",translation:"Mumpung sudah datang, mari melihat-lihat dengan santai."},
  "わざわざ":{reading:"わざわざ",meaning:"sengaja sampai repot-repot",example:"わざわざ来てくれてありがとう。",translation:"Terima kasih sudah sengaja datang."},
  "うっかり":{reading:"うっかり",meaning:"tanpa sengaja karena lengah",example:"うっかり約束を忘れました。",translation:"Saya tanpa sengaja lupa janji."},
  "事情":{reading:"じじょう",meaning:"keadaan / alasan tertentu",example:"事情があって会社を休みました。",translation:"Saya libur kerja karena ada keadaan tertentu."},
  "対象":{reading:"たいしょう",meaning:"sasaran / yang memenuhi syarat",example:"この割引は学生が対象です。",translation:"Diskon ini ditujukan untuk pelajar."}
};

const q=(id,section,type,prompt,options,answer,explanation,terms=[],extra={})=>({id,section,type,prompt,options,answer,explanation,terms,...extra});
window.N3_QUESTIONS=[
  q('v01','vocab','kanji-reading','会議の時間を【確認】してください。',['かくにん','かくねん','かんにん','かんねん'],0,'確認（かくにん） berarti memastikan atau mengonfirmasi.',['確認']),
  q('v02','vocab','kanji-reading','電車は予定より遅れて【到着】した。',['とうちゃく','どうちゃく','とうじゃく','どうじゃく'],0,'到着 dibaca とうちゃく dan berarti tiba.',['到着']),
  q('v03','vocab','kanji-reading','旅行の【準備】を始める。',['じゅんび','じゅびん','じゅんぴ','じゅび'],0,'準備 dibaca じゅんび. Perhatikan rendaku pada 備 = び.',['準備']),
  q('v04','vocab','orthography','台風のため、試合はえんきになった。',['延気','延期','遠期','遠気'],1,'えんき ditulis 延期, yaitu penundaan.',['延期']),
  q('v05','vocab','orthography','レポートのしめきりは来週です。',['締切','閉切','締入','閉入'],0,'しめきり ditulis 締切 dan berarti deadline.',['締切']),
  q('v06','vocab','orthography','最近、この町では人口がげんしょうしている。',['減少','限少','減小','限小'],0,'げんしょう ditulis 減少, lawan katanya 増加.',['減少','増加']),
  q('v07','vocab','context','この薬を飲んでも、あまり（　）がなかった。',['効果','結果','都合','機会'],0,'Obat memiliki 効果 (khasiat/efek). 結果 adalah hasil.',['効果']),
  q('v08','vocab','context','朝の電車はとても（　）していて、座れない。',['混雑','故障','到着','減少'],0,'Kereta yang penuh sesak disebut 混雑している.',['混雑','故障']),
  q('v09','vocab','context','この仕事に（　）するには、ネットで書類を送ってください。',['応募','利用','提出','変更'],0,'応募する berarti melamar atau mendaftar pada posisi/lomba.',['応募','提出']),
  q('v10','vocab','context','エアコンが（　）したので、修理を頼んだ。',['故障','混雑','延期','増加'],0,'Mesin yang rusak menggunakan 故障する.',['故障']),
  q('v11','vocab','paraphrase','田中さんは誘いを断った。',['誘いを受けた','誘いを忘れた','誘いを拒否した','誘いを説明した'],2,'断る paling dekat artinya dengan 拒否する: menolak.',['断る']),
  q('v12','vocab','paraphrase','念のため、コピーも持ってきてください。',['急いで','何度も','必要かもしれないので','絶対に必要なので'],2,'念のため menyatakan tindakan berjaga-jaga.',['念のため']),
  q('v13','vocab','usage','「せっかく」の使い方として最もよいものはどれですか。',['せっかく雨が降ったので、服がぬれた。','せっかく日本へ来たので、京都にも行きたい。','せっかく寝たら、すぐ朝になった。','せっかく安いので、品質が悪い。'],1,'せっかく menyoroti kesempatan/usaha berharga yang hendak dimanfaatkan.',['せっかく']),
  q('v14','vocab','usage','「うっかり」の使い方として最もよいものはどれですか。',['うっかり勉強して合格した。','うっかり電気を消し忘れた。','うっかり丁寧に説明した。','うっかり毎日運動している。'],1,'うっかり dipakai untuk kesalahan karena lengah.',['うっかり']),
  q('v15','vocab','context','雨が降るかもしれないので、（　）傘を持っていく。',['とうとう','念のため','まもなく','せっかく'],1,'Membawa payung untuk berjaga-jaga: 念のため.',['念のため']),
  q('v16','vocab','context','友達が（　）駅まで迎えに来てくれた。',['わざわざ','だんだん','ますます','そろそろ'],0,'わざわざ menekankan bahwa teman sengaja datang sampai repot-repot.',['わざわざ']),

  q('g01','grammar','form','日本に来て（　）、もう三年になります。',['から','まで','ほど','だけ'],0,'Vてから menunjukkan titik awal waktu: sudah tiga tahun sejak datang ke Jepang.'),
  q('g02','grammar','form','この店は駅から近い（　）、値段も安い。',['ために','うえに','ほどに','ところに'],1,'～うえに menambahkan alasan/kelebihan searah: dekat, ditambah murah.'),
  q('g03','grammar','form','明日は早いから、今日は夜更かししない（　）がいい。',['こと','もの','ほう','わけ'],2,'～ほうがいい adalah saran: sebaiknya tidak begadang.'),
  q('g04','grammar','form','雨が降っている（　）、彼は傘を持たずに出かけた。',['のに','ので','なら','まで'],0,'～のに menyatakan hasil yang berlawanan dari dugaan: meski hujan, pergi tanpa payung.'),
  q('g05','grammar','form','このボタンを押す（　）、ドアが開きます。',['なら','と','ても','ながら'],1,'～と menyatakan hasil otomatis/selalu terjadi.'),
  q('g06','grammar','form','財布を忘れたので、同僚にお金を貸して（　）。',['あげた','くれた','もらった','やった'],2,'Subjek menerima bantuan dari rekan: Vてもらった.'),
  q('g07','grammar','form','健康の（　）、毎朝30分歩いています。',['ように','ために','らしく','ところで'],1,'Nのために berarti demi/untuk tujuan kesehatan.'),
  q('g08','grammar','form','山田さんは来月会社を辞める（　）です。',['こと','もの','そう','ため'],2,'Bentuk biasa + そうだ menyampaikan informasi yang didengar.'),
  q('g09','grammar','form','説明を読めば、使い方が分かる（　）です。',['はず','べき','つもり','ばかり'],0,'～はずだ menyatakan perkiraan logis: kalau membaca petunjuk, semestinya paham.'),
  q('g10','grammar','form','この料理は辛すぎて、私には食べ（　）。',['きれない','かけない','おわらない','つづけない'],0,'Vます + きれない berarti tidak sanggup menyelesaikan sepenuhnya.'),
  q('g11','grammar','composition','言葉を並べ替えて、★に入るものを選んでください。\nこの本は、日本（　）（　）★（　）一冊です。',['文化を','役に立つ','知るのに','とても'],1,'Urutan: 日本文化を 知るのに とても 役に立つ 一冊です。 ★ adalah 役に立つ.'),
  q('g12','grammar','composition','言葉を並べ替えて、★に入るものを選んでください。\n私は（　）（　）★（　）と思っています。',['日本で','働きたい','将来','と'],1,'Urutan: 私は将来 日本で 働きたい と 思っています。 ★ adalah 働きたい.'),
  q('g13','grammar','composition','言葉を並べ替えて、★に入るものを選んでください。\nこの仕事は（　）（　）★（　）できません。',['一人では','終わらせる','とても','ことが'],1,'Urutan: この仕事は一人では とても 終わらせる ことができません。 ★ adalah 終わらせる.'),
  q('g14','grammar','text','A「コピー機が動かないんですが。」\nB「紙が入っているか確認しましたか。」\nA「はい。（　）、動きません。」',['それで','それなのに','それなら','それとも'],1,'それなのに menghubungkan fakta yang bertentangan: sudah dicek, tetapi tetap tidak bekerja.'),
  q('g15','grammar','text','最初はこの仕事が難しいと思いました。（　）、毎日練習するうちに慣れてきました。',['しかし','つまり','そのため','例えば'],0,'Namun, setelah berlatih setiap hari menjadi terbiasa: しかし.'),
  q('g16','grammar','text','この地域ではバスが一時間に一本しかない。（　）、車を利用する人が多い。',['一方で','そのため','ところが','それでも'],1,'Kalimat kedua adalah akibat; gunakan そのため.'),

  q('r01','reading','short','問題に答えてください。',['7月10日','7月11日','7月12日','7月13日'],2,'Pesan dikirim Jumat 10 Juli dan rapat dipindah ke “minggu depan hari Minggu”, yaitu 12 Juli.', ['変更','確認'],{passage:'田中さんへ\n来週の日曜日に予定していた会議ですが、会場の都合で午後2時から4時に変更になりました。場所は前と同じです。参加できない場合は、今週の金曜日（7月10日）までに連絡してください。\n会議は何月何日ですか。'}),
  q('r02','reading','short','筆者が一番言いたいことは何ですか。',['朝食は短時間で食べるべきだ','朝食の内容より時間が重要だ','簡単でも朝食を取ったほうがよい','朝は水だけで十分だ'],2,'Penulis menegaskan bahwa sarapan sederhana pun lebih baik daripada tidak makan.',[],{passage:'忙しい朝、朝食を食べない人も多い。しかし、何も食べないと午前中に集中できなくなることがある。豪華な料理を作る必要はない。バナナやパンなど、簡単なものでも食べることが大切だ。'}),
  q('r03','reading','short','佐藤さんはどうして店に電話しますか。',['商品を注文するため','営業時間を確認するため','返品できるか聞くため','店の場所を聞くため'],2,'Ukuran salah dan ingin menukar; ia menelepon untuk memastikan apakah pengembalian/penukaran memungkinkan.', ['確認'],{passage:'佐藤さんは昨日、インターネットで買った靴を受け取った。しかし、注文したサイズと違っていた。店のサイトには「商品到着後7日以内にご連絡ください」と書いてある。佐藤さんは今日、店に電話することにした。'}),
  q('r04','reading','mid','この文章によると、昼休みに散歩するよさは何ですか。',['仕事の時間が短くなる','午後の集中力が戻りやすい','同僚と話さなくてよい','昼ご飯を食べなくてよい'],1,'Teks menyebut pergantian suasana melalui jalan singkat membantu konsentrasi pulih.', ['効果','環境'],{passage:'在宅勤務では、通勤時間がなく便利な一方、仕事と休みの区別がつきにくい。昼休みも机の前で過ごすと、十分に休んだ気がしないことがある。そこで私は、昼ご飯のあとに10分だけ近所を歩くようにした。短い時間でも外の空気に触れて景色を見ると、気分が変わり、午後の仕事に集中しやすくなった。大切なのは長く運動することではなく、意識して環境を変えることだと思う。'}),
  q('r05','reading','mid','筆者の考えに合うものはどれですか。',['失敗した言葉だけを何度も読む','新しい言葉は一日に全部覚える','思い出す練習を日を空けて行う','分からない言葉はすぐ答えを見る'],2,'Penulis merekomendasikan mencoba mengingat, memeriksa, lalu mengulang di hari berbeda.', ['経験'],{passage:'外国語の単語を覚えるとき、単語帳を何度も読むだけでは、覚えた気になることがある。しかし、本を閉じて意味を思い出そうとすると、意外に出てこない。私はまず答えを見ずに思い出し、間違えたら確認する。そして同じ単語を翌日や数日後にもう一度試す。この方法は少し大変だが、試験のときに必要な「自分で思い出す力」がつく。'}),
  q('r06','reading','information','土曜日の午前10時に、一人で初めて利用したい人はどうしますか。',['予約せず300円払う','前日までに予約して300円払う','予約せず500円払う','前日までに予約して500円払う'],3,'Akhir pekan biayanya 500 yen dan pemula wajib reservasi sehari sebelumnya.', ['利用','対象'],{passage:'市民スポーツ室\n利用時間：平日 9:00〜20:00／土日 9:00〜17:00\n料金：平日300円・土日500円\n初めての方は説明を受けるため、前日までに予約してください。経験者は予約不要です。毎月第3日曜日は休みです。'}),
  q('r07','reading','information','学生のミラさんが申し込む場合、必要でないものはどれですか。',['申込書','学生証のコピー','顔写真','先生の推薦状'],3,'Pengumuman meminta formulir, foto, dan salinan kartu pelajar; rekomendasi guru tidak disebut.', ['応募','提出','対象'],{passage:'日本語スピーチ大会 参加者募集\n対象：市内の学校で日本語を学ぶ学生\n提出物：申込書、顔写真1枚、学生証のコピー\n締切：9月15日（必着）\n申込書は市のホームページからダウンロードできます。'}),
  q('r08','reading','long','筆者がこの経験から学んだことは何ですか。',['便利な道具は使わないほうがよい','計画は絶対に変えてはいけない','目的に合わせて方法を見直すことが大切だ','一人で勉強するほうが効率がよい'],2,'Kesimpulan menekankan bahwa cara adalah alat dan perlu ditinjau ulang sesuai tujuan.', ['効果','経験','変更'],{passage:'私は以前、毎日決めた数の漢字を書くことを目標にしていた。ノートが何冊も増えると勉強した気分になったが、文章を読むと、書いたはずの漢字の意味が思い出せなかった。そこで、書く回数を減らし、その漢字を使った短い文を作ったり、数日後に読み方をテストしたりする方法に変えた。最初は進む量が減ったように感じた。しかし一か月後、以前より文章が読みやすくなっていることに気づいた。勉強法は続けることも大切だが、目的に近づいているか時々確認しなければならない。方法そのものが目的になってはいけないのだ。'}),

  q('l01','listening','quick','音声を聞いて、最もよい返事を選んでください。',['はい、お大事に。','はい、気をつけます。','いいえ、元気でした。'],1,'「気をつけて」への自然な返答は「はい、気をつけます」。',[],{audio:'帰り道、暗いから気をつけてね。'}),
  q('l02','listening','quick','音声を聞いて、最もよい返事を選んでください。',['もう提出しました。','まだ読みません。','きっと書きません。'],0,'締切について聞かれ、「もう提出しました」が適切。',['締切','提出'],{audio:'レポートの締切、明日ですよね。'}),
  q('l03','listening','quick','音声を聞いて、最もよい返事を選んでください。',['では、お先に失礼します。','どうぞ、おかまいなく。','いいえ、こちらこそ。'],2,'Ucapan terima kasih dibalas dengan いいえ、こちらこそ。',[],{audio:'今日は手伝ってくださって、ありがとうございました。'}),
  q('l04','listening','point','女の人はこのあと、まず何をしますか。',['会議室へ行く','資料をコピーする','部長に電話する','メールを送る'],1,'Pertama menggandakan dokumen, lalu membawanya ke ruang rapat.', ['準備'],{audio:'男：会議の準備、もうできた？\n女：部屋は予約しました。これから資料を20部コピーして、会議室へ持っていきます。\n男：じゃあ、僕は部長に連絡するね。'}),
  q('l05','listening','point','男の人は何時ごろ駅に着きますか。',['6時','6時15分','6時30分','7時'],2,'Kereta terlambat 30 menit dari rencana pukul enam, jadi tiba sekitar 6:30.', ['到着'],{audio:'男：今、電車の中なんだけど、事故で30分ぐらい遅れているんだ。6時に着く予定だったけど、少し待っていて。\n女：分かった。駅のカフェにいるね。'}),
  q('l06','listening','task','女の人は何を持っていきますか。',['飲み物だけ','食べ物だけ','飲み物と皿','食べ物と皿'],2,'Makanan disediakan; ia diminta membawa minuman dan piring kertas.',[],{audio:'男：明日のパーティー、食べ物は僕が準備するよ。\n女：じゃあ、私は飲み物を持っていくね。\n男：助かる。紙のお皿もお願いできる？\n女：うん、分かった。'}),
  q('l07','listening','task','男の人はこのあとどうしますか。',['病院へ行く','会社へ戻る','家で休む','薬局で働く'],0,'Gejala sudah lama dan disarankan periksa ke rumah sakit; pria menyetujuinya.',[],{audio:'女：そのせき、まだ治らないの？\n男：うん、薬局の薬を飲んでいるんだけど。\n女：もう一週間でしょう。一度病院で見てもらったほうがいいよ。\n男：そうだね。今日、仕事の帰りに行ってみる。'}),
  q('l08','listening','outline','女の人が一番伝えたいことは何ですか。',['毎日長時間勉強すべきだ','短くても勉強を続けるとよい','朝だけ勉強するとよい','難しい本を読むべきだ'],1,'Inti pembicaraan adalah konsistensi singkat lebih baik daripada rencana panjang yang tak dijalankan.', ['効果'],{audio:'私は以前、週末に三時間勉強しようと決めていました。でも、忙しくてできない週が多かったんです。今は毎朝15分だけ復習しています。短いので始めやすく、毎日続けられます。少しずつでも続けるほうが、私には効果がありました。'}),
  q('l09','listening','verbal','店員は何と言いますか。',['こちらにお名前をお書きください。','お名前を書いていただきました。','お名前を書いたことがあります。'],0,'Permintaan sopan kepada pelanggan: お書きください.',[],{audio:'レストランが満席です。店員は待っているお客さんに、紙に名前を書いてほしいです。何と言いますか。'}),
  q('l10','listening','outline','二人は何について話していますか。',['旅行の場所','新しい仕事','引っ越しの理由','電車の故障'],2,'Pembicaraan berpusat pada alasan pindah rumah: tempat kerja jauh dan kereta padat.', ['混雑'],{audio:'女：来月、駅の近くに引っ越すんだって？\n男：うん。今の家は静かで好きなんだけど、会社まで一時間半かかるから。\n女：毎朝の電車も混んでいるしね。\n男：そう。今度は歩いて会社へ行けるんだ。'})
];
